### ISSUE TITLE
Force calculation failing for Nequip due to no grad function

### ISSUE THREAD

**Issue by jeevster** [jvita/data_efficiency_in_IAPS#1]
I am attempting to generate a loss landscape for a Nequip model I have trained by running "ip_explorer/landscape/__main__.py". When ip_explorer/models/nequip.py attempts to make a forward pass through the network in the compute_loss function, the following error arises: "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn".

This is occurring because the "total_energy" output field of the model for some reason did not record the gradient history of the forward pass. Therefore when we try to differentiate the energy with torch.autograd.grad to calculate forces, there is an error.

I have verified that this same model can correctly calculate forces and perform MD simulation in my own codebases. 

The command I am running is this:
python __main__.py \
--num-nodes=1 \
--save-dir /home/sanjeevr/implicit-md/landscapes \
--model-type=nequip --database-path=/home/sanjeevr/MDsim/MODELPATH/nequip/md17-aspirin_10k_nequip \
--model-path=/home/sanjeevr/MDsim/MODELPATH/nequip/md17-aspirin_10k_nequip \
--landscape-type=plane \
--no-compute-initial-losses \
--steps=10

Any ideas on why this may be occurring? I think it could be due to the way the model is being wrapped in the SimpleModelWrapper. Could it be that I'm not passing in other necessary command line arguments?

**Comment by jvita** [comment]
Moved issue to code repo
